### ISSUE TITLE
[documentation] Bad references to \Amp\Promise in documenttion

### ISSUE THREAD

**Issue by gauthier-scano** [amphp/amphp.org#7]
Hello,

Maybe I'm wrong but I would like to advise you that the document at https://amphp.org/amp still have references to \Amp\Promise for awaitAll, awaitFirst and awaitAny.  

Shouldn't it be "Amp\Future" instead of "Amp\Promise" for these 3 functions ?

Regards

**Comment by kelunik** [comment]
You're completely right. Mind sending a pull request to amphp/amp's README?

**Comment by gauthier-scano** [comment]
Done ! Here is the related link of the pull request : https://github.com/amphp/amphp.org/pull/8

**Comment by kelunik** [comment]
Thank you! The docs in this repo / the website should automatically update soon. 🙂

**Comment by gauthier-scano** [comment]
Nice ! Thank you for your feedback.

**Comment by gauthier-scano** [comment]
Reopening because it looks like website did not auto-update.

(I checked and it's not a local browser cache issue)

**Comment by kelunik** [comment]
Sorry, this was an oversight. https://github.com/amphp/amphp.org/pull/8/files is a PR in this repository, but it should have been to the README at https://github.com/amphp/amp/blob/3.x/README.md

The automatic sync reverted your change: https://github.com/amphp/amphp.org/commit/bf52ec2ba927f072ee4bc72b35724ed232ff1427

**Comment by gauthier-scano** [comment]
Oh ok, do I have anything to do ?

**Comment by kelunik** [comment]
It'd be wonderful if you could reopen the PR against https://github.com/amphp/amp/blob/3.x/README.md, yes.

**Comment by gauthier-scano** [comment]
Didn't have the right to reopen, I have created a new one.

**Comment by kelunik** [comment]
You opened it in the wrong repository. You need to edit the readme in amphp/amp, not this repository.

**Comment by gauthier-scano** [comment]
My bad, it's done.

**Comment by kelunik** [comment]
I don't see a new PR, what am I missing?

**Comment by kelunik** [comment]
It's here now, thanks!
